do not show warnings for semesters in closed years
sandboxnu/graduatenu pull request #163
Opened 2020-09-29 23:28 UTC by NilsBacke

2020-09-29 23:28 UTC, NilsBacke commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent error popups from showing up on closed years](https://trello.com/c/grwecl6O/152-prevent-error-popups-from-showing-up-on-closed-years)

2020-10-07 22:13 UTC, imanmoreira requested changes
I just realized I forgot to submit the review, sorry these took so long

2020-10-08 02:52 UTC, NilsBacke commented on frontend/src/state/reducers/scheduleReducer.ts
> +      case getType(setClosedYearsToYearsInThePast): {
I believe the problem with that is that there is not necessarily a `draft.present.schedule` when a user sets their academic year. Correct me if I'm wrong though.

2020-10-11 02:37 UTC, imanmoreira approved these changes

2020-10-11 02:37 UTC, merged