Add Template plans
sandboxnu/graduatenu pull request #192
Opened 2020-11-12 02:52 UTC by NilsBacke

2020-11-12 02:52 UTC, NilsBacke commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create template plans model and add fields onto existing plans model](https://trello.com/c/v4EVkWzP/176-create-template-plans-model-and-add-fields-onto-existing-plans-model)

2020-11-12 23:20 UTC, imanmoreira approved these changes

2020-11-12 23:20 UTC, imanmoreira reviewed
I think you have it set to merge into annotate so you might want to switch it to master

2020-11-12 23:27 UTC, imanmoreira requested changes

2020-11-12 23:27 UTC, imanmoreira commented on api/db/schema.rb
> +    t.string "plan_string", null: false
Let's switch plan_string to coop_cycle, since now we have "plans" which are schedules that a user has

2020-11-21 16:33 UTC, imanmoreira approved these changes

2020-11-26 03:50 UTC, merged