add plan popper improvements
sandboxnu/graduatenu pull request #261
Opened 2020-12-24 17:09 UTC by NilsBacke

See trello card for acceptance criteria

2020-12-24 17:09 UTC, NilsBacke commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Plan Popper Refinements](https://trello.com/c/veXPxeO6/274-add-plan-popper-refinements)

2020-12-25 18:08 UTC, imanmoreira requested changes

2020-12-25 18:08 UTC, imanmoreira commented on frontend/src/home/AddPlanPopper.tsx
> +        value={selectedCatalogYear ? String(selectedCatalogYear) : ""}
NIT: I think you can pass it in selectedCatalogYear directly since `value` can be null.

2020-12-26 20:20 UTC, NilsBacke commented on frontend/src/home/AddPlanPopper.tsx
>            <TextField {...params} variant="outlined" label="Major" fullWidth />
Good catch!!!

2020-12-27 17:30 UTC, imanmoreira approved these changes

2020-12-27 17:49 UTC, merged