Advisor plan of study upload
sandboxnu/graduatenu pull request #333
Opened 2021-04-01 06:11 UTC by andrewjleung

2021-04-11 16:36 UTC, imanmoreira reviewed
Can't find exactly where in the code it is but for the uploading excel spreadsheets, I don't think it should be mandatory to select a major, since it could be several majors

2021-04-11 16:44 UTC, imanmoreira requested changes
Other than the small change about majors, this looks amazing and it works great!

2021-04-11 17:15 UTC, andrewjleung commented
@imanmoreira I initially didn't include major but it was rejected by the templates API since it was required, all the fields that are on the popper are there because the API required them

2021-04-22 19:42 UTC, imanmoreira approved these changes

2021-04-22 23:28 UTC, merged