Majors - Backend
sandboxnu/graduatenu pull request #507
Opened 2022-11-30 21:55 UTC by aryanshah701

# Description

## Context
- We need a solid way of dong the following things
  - Storing major objects
  - Retrieving major objects by major name and catalog year
  - Knowing which majors we support and for which years
  - Carefully update/create our plans ensuring we only allow plans that are storing the supported majors 

- This whole thing can easily be a design discussion and will be in the future. However, for now, we need to simply address these things in a way that isn't fully jank, works, and hopefully requires minimal changes in a scoped area in the future once we finalize the design.

- I think the following are sound design choices 
  - Our frontend should be able to dynamically update the supported majors list. It shouldn't rely on a static object. 
  - Our majors should be stored somewhere on the server. As we scale to 100s of majors, bundling all of them in our frontend bundle is bad.

- My approach focuses on 2 things: Simplicity since we don't have time lol, and the above 2 acceptance criteria.

## My Approach
This is how we achieve things based on my approach
  - Storing major objects: JSON for simplicity, we should move to db at some point and link plans to majors using a foreign key imo.
  - Retrieving major objects by major name and catalog year:  API endpoint, since majors are stored on the server.
  - Knowing which majors we support and for which years:
    - API endpoint, server is the source of truth for the majors we support. 
    - For now, we return a static object but in the future once the majors are in a db, we could query our db for the major names etc that we support thereby truly making it dynamic.
    -  Every time we update our db with a new major, our frontend will automatically support creating plans with it without any need for redeploying the frontend BOOM.
  - Carefully update/create our plans ensuring we only allow plans that are storing the supported majors: Validation done on the server since the server knows which majors it supports.

## Changes
- New bscs 2022 major, I should have done 2021 but did 2022 by mistake. I will add 2021 later.
- Major module for get major and get supported major endpoint.
- Update plan create and update services to validate major, year pair.
- Fix plan get endpoint. It was previously throwing a 500 when we request a plan that doesn't exist. Now it throws a forbidden, since a plan that doesn't exist isn't owned by anyone lol. 

## Type of change

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I tried to write e2e API tests, failed miserably. Debugging our e2e test was taking too long so I tested manually, I created a ticket to fix e2e tests.

- Get major
<img width="1440" alt="major-invalid-name" src="https://user-images.githubusercontent.com/30478978/204915450-162f644f-3f8c-4f0a-b972-66e0f8e71d47.png">
<img width="1440" alt="major-invalid-year" src="https://user-images.githubusercontent.com/30478978/204915460-9a135f20-010c-4e62-98e2-c739f79a4790.png">
<img width="1439" alt="major-valid" src="https://user-images.githubusercontent.com/30478978/204915471-a24ce773-b9bc-4059-bd71-6cc90e031e43.png">

- Get supported majors
<img width="1439" alt="supported_majors" src="https://user-images.githubusercontent.com/30478978/204915497-23076557-c91d-4279-86fb-76455a721609.png">

- Create plan
<img width="1437" alt="create-plan-invalid-year" src="https://user-images.githubusercontent.com/30478978/204915520-bafdc377-b3c4-4eac-b0f0-795cdfbda581.png">
<img width="1440" alt="create-plan-invalid-name" src="https://user-images.githubusercontent.com/30478978/204915535-2ee29725-96d5-4c8d-b714-2a217b7395a0.png">
<img width="1440" alt="create-plan-valid" src="https://user-images.githubusercontent.com/30478978/204915544-35bf979b-6053-429c-90fa-36c21ffa494c.png">

- Update plan
<img width="1439" alt="update-plan-invalid-year" src="https://user-images.githubusercontent.com/30478978/204915567-dd9f60a5-e8e0-42fa-8abf-08fb155601d9.png">
<img width="1440" alt="update-plan-invalid-name" src="https://user-images.githubusercontent.com/30478978/204915574-63ccc5cd-8cff-4b27-823b-c631bd817733.png">
<img width="1440" alt="update-plan-valid" src="https://user-images.githubusercontent.com/30478978/204915585-002f7ca7-b41d-4d86-8909-8d79cfb53693.png">

- [Bug fix] Get plan with invalid id
<img width="1434" alt="get-plan-with-invalid-id" src="https://user-images.githubusercontent.com/30478978/204915601-336f596a-7327-4c22-9b8f-49cda1b506fd.png">

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-30 23:01 UTC, BrandonLim8890 approved these changes
Haven't yet taken a look at the JSON file, but from a code perspective it looks good. Will take a deeper dive into the JSON before standup

2022-12-02 01:55 UTC, aryanshah701 commented on packages/api-v2/src/major/major.controller.ts
> +  @Get("supportedMajors")
TRUUUEEEEE

2022-12-02 02:30 UTC, BrandonLim8890 requested changes
Small changes to JSON but overall looks good!

2022-12-02 02:30 UTC, BrandonLim8890 commented on packages/api-v2/src/major/majors/2022/bscs.json
> +          ]
Duplicate from above. Can remove

2022-12-02 02:30 UTC, BrandonLim8890 commented on packages/api-v2/src/major/majors/2022/bscs.json
> +    },
Missing security required courses
<img width="719" alt="image" src="https://user-images.githubusercontent.com/20124104/205201304-2c274563-81f9-4e17-b06b-bed91c505b6c.png">

2022-12-03 02:32 UTC, merged