Milo/duplicate plan button
sandboxnu/graduatenu pull request #707
Opened 2024-02-11 20:59 UTC by yijen-sun

# Description
Added duplicate plan button that creates a copy of the current plan as a new plan.
Disabled the Add Plan button and the Duplicate Plan button on guest mode when the maximum number of plans (5) has been reached. This is because the local storage that guest data is stored on is limited and will cause issues lol

https://github.com/sandboxnu/graduatenu/assets/94196677/936db3f7-a3bf-4d8a-af8e-870569c24ac6

Closes #690 

## Type of change

Please tick the boxes that best match your changes.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [ ] This has migration changes and requires a run of `yarn dev:migration:run`

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests) Provide instructions so we can reproduce.

Manually tested 

# Checklist:

- [X] I have run the production builds in docker for the frontend/backend and ensure things run fine. Check README of repo on how to run if not sure.
- [X] I have performed a self-review of my own code
- [X] I have commented my code where needed
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I've run the end to end tests
- [X] Any dependent changes have been merged and published in downstream modules

2024-02-14 17:56 UTC, AngelaZQ1 commented
404k additions 💀

2024-02-14 18:49 UTC, KobeZ123 requested changes

2024-02-14 18:49 UTC, KobeZ123 commented on 46mb.json
should this file be deleted? i'm assuming it's the local storage data.

2024-02-14 18:49 UTC, KobeZ123 commented on ls.json
are we keeping this test plan for reference?

2024-02-14 18:49 UTC, KobeZ123 commented on packages/frontend/components/Plan/DuplicatePlanButton.tsx
> +    // TODO: figure out when to do with this -- debounce stuff
is this TODO still relevant? i think adding the plan limit was our solution, right?

2024-02-14 18:49 UTC, KobeZ123 commented on packages/frontend/pages/home.tsx
> +  // createEmptySchedule,
we can remove this

2024-02-25 19:52 UTC, KobeZ123 approved these changes
Nice work!

2024-02-25 19:52 UTC, merged