minor endpoints folder, types, and missing data
sandboxnu/graduatenu pull request #767
Opened 2024-11-12 20:57 UTC by hellolol2016

# Description

I added minor endpoints (pretty much refactoring the major folder). Added a couple of types for minors, will need to be heavily reviewed.

Closes # (issue number)

## Type of change

Please tick the boxes that best match your changes.. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [ ] This has migration changes and requires a run of `yarn dev:migration:run`

# How Has This Been Tested?

This has not been tested yet, Kobe will teach me at the next standup

# Checklist:

- [ ] I have run the production builds in docker for the frontend/backend and ensure things run fine. Check README of repo on how to run if not sure.
- [x] I have performed a self-review of my own code
- [x] I have commented my code where needed
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I've run the end to end tests
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-24 20:27 UTC, hellolol2016 commented
HAS NOW BEEN TESTED. API ENDPOINT WORKS

2024-12-04 00:40 UTC, KobeZ123 requested changes

2024-12-04 00:40 UTC, KobeZ123 commented on packages/api/src/minor/minor.service.ts
> +    //const supportedMinors: SupportedMinors = MINORS;
we can remove this

2024-12-04 00:40 UTC, KobeZ123 commented on packages/common/src/types.ts
> +export type SupportedMinors = Record<string, Record<string, Minor>>;
we can consolidate the representation Record<string, SupportedMinjorsForYear>

2024-12-08 20:37 UTC, KobeZ123 approved these changes

2024-12-08 20:37 UTC, merged